services:
  nginx:
    image: nginx
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  order-app-1:
    image: order-service
    restart: always

  order-app-2:
    image: order-service
    restart: always

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management

  mysql:
    image: mysql
